Repository WhatDoYouSing/WhatDoYouSing-App, pull requests merged in 2025-02, with the labels that each got.

#9 [Chore/#5] 아이콘 컴포넌트 추가
  assets/svgs/IcArrowDown.tsx
  assets/svgs/IcArrowLeft.tsx
  assets/svgs/IcArrowRight.tsx
  assets/svgs/IcArrowUp.tsx
  assets/svgs/IcCalendarOff.tsx
  assets/svgs/IcCalendarOn.tsx
  assets/svgs/IcCheckOff.tsx
  assets/svgs/IcCheckOn.tsx
  assets/svgs/IcCommentOff.tsx
  assets/svgs/IcCommentOn.tsx
  assets/svgs/IcCommunity.tsx
  assets/svgs/IcEye.tsx
  assets/svgs/IcFilterOff.tsx
  assets/svgs/IcFilterOn.tsx
  assets/svgs/IcFocusOff.tsx
  assets/svgs/IcFocusOn.tsx
  assets/svgs/IcHidden.tsx
  assets/svgs/IcKebab.tsx
  assets/svgs/IcLikeOff.tsx
  assets/svgs/IcLikeOn.tsx
  assets/svgs/IcLocation.tsx
  assets/svgs/IcMapOff.tsx
  assets/svgs/IcMapOn.tsx
  assets/svgs/IcMy.tsx
  assets/svgs/IcNotification.tsx
  assets/svgs/IcPlus.tsx
  assets/svgs/IcRecord.tsx
  assets/svgs/IcSaveOff.tsx
  assets/svgs/IcSaveOn.tsx
  assets/svgs/IcSearch.tsx
  assets/svgs/IcSelectOff.tsx
  assets/svgs/IcSelectOn.tsx
  assets/svgs/IcSend.tsx
  assets/svgs/IcSetting.tsx
  assets/svgs/IcTag.tsx
  assets/svgs/IcTop.tsx
  assets/svgs/IcUpload.tsx
  assets/svgs/IcViewAll.tsx
  assets/svgs/IcViewFriends.tsx
  assets/svgs/IcViewOnlyMe.tsx
  assets/svgs/IcX.tsx
  assets/svgs/index.ts
  global.d.ts
  package-lock.json
  package.json
Labels: ✨Feature, 🎸서연

#14 [Feat/#13] nativewind 세팅 및 디자인 시스템 구축
  app.d.ts
  app/_layout.tsx
  app/details.tsx
  app/index.tsx
  babel.config.js
  components/common/Typo.tsx
  global.css
  metro.config.js
  nativewind-env.d.ts
  package-lock.json
  package.json
  portcss.config.js
  styles/ThemeProvider.tsx
  styles/colors.ts
  styles/fonts.ts
  styles/globalStyles.ts
  styles/typography.css
  tailwind.config.ts
  tsconfig.json
Labels: ⚙️Setting, 🎧지혜

#16 [Feat/#12] 헤더 / 하단 네비게이션 바 구현
  .github/pull_request_template.md
  app/_layout.tsx
  app/details.tsx
  app/index.tsx
  app/screens/HomeScreen.tsx
  app/screens/MyScreen.tsx
  app/screens/RecordScreen.tsx
  app/screens/UploadScreen.tsx
  assets/svgs/IcCommunity.tsx
  assets/svgs/IcMy.tsx
  assets/svgs/IcRecord.tsx
  assets/svgs/IcUpload.tsx
  babel.config.js
  components/common/Header.tsx
  components/common/index.ts
  navigation/BottomNavigator.tsx
  navigation/StackNavigator.tsx
  tsconfig.json
Labels: ✨Feature, 🎸서연

#19 [Feat/#7] 노트 카드 및 플리 카드 구현
  .expo/devices.json
  .expo/types/CardType.ts
  .expo/types/router.d.ts
  .expo/web/cache/production/images/favicon/favicon-943f571092de6e1842992bc03e54e8de780d9f24bde623d47ce1968c2bc13a14-contain-transparent/favicon-48.png
  .gitignore
  components/common/Card/DashedBorder.tsx
  components/common/Card/NoteCard.tsx
  components/common/Card/PlaylistCard.tsx
  components/common/Card/PlaylistInfo.tsx
  components/common/Card/ProfileHeader.tsx
  components/common/Card/QuoteCard.tsx
  components/common/Card/SongInfo.tsx
  components/common/Card/noteMock.ts
  components/common/Typo.tsx
  components/common/index.ts
  styles/colors.ts
  styles/typography.css
  tailwind.config.ts
Labels: ✨Feature, 🎧지혜

#25 [Feat/#24] 버튼 공통 컴포넌트 구현
  components/common/FilledButton.tsx
  components/common/index.ts
Labels: ✨Feature, 🎸서연

#18 [Feat/#17] 하단 메뉴 공통 컴포넌트 구현
  components/common/BottomMenu.tsx
  components/common/index.ts
  navigation/BottomNavigator.tsx
Labels: ✨Feature, 🎸서연

#27 [Feat/#26] 중첩 네비게이션 구조 설계
  app/_layout.tsx
  app/home/HomeScreen.tsx
  app/my/MyScreen.tsx
  app/record/RecordScreen.tsx
  app/upload/UploadNoteScreen.tsx
  app/upload/UploadPlaylistScreen.tsx
  navigation/BottomNavigator.tsx
  navigation/StackNavigator.tsx
  navigation/UploadStackNavigator.tsx
Labels: ✨Feature, 🎸서연

#28 [Feat/#6] 공통 모달 및 태그/감정칩
  app/index.tsx
  babel.config.js
  components/common/BaseModal.tsx
  components/common/BottomModal.tsx
  components/common/Tags/Chip.tsx
  components/common/Tags/EmotionDetailTags.tsx
  components/common/Tags/EmotionModal.tsx
  components/common/Tags/FilterTags.tsx
  components/common/Tags/Tag.tsx
  components/common/Tags/TagSection.tsx
  components/common/index.ts
  constants/.gitkeep
  constants/emotions.ts
  constants/tag.ts
  hooks/useEmotions.ts
  package-lock.json
  package.json
  utils/cn.ts
Labels: ✨Feature, 🎵지원

#29 [Feat/#23] 홈 (커뮤니티) 탭 퍼블리싱
  app/home/HomeScreen.tsx
  components/Home/CtgryDropdown.tsx
  components/Home/CtgryTopBar.tsx
  components/common/Card/NoteCard.tsx
  components/common/Card/PlaylistCard.tsx
  components/common/Card/PlaylistInfo.tsx
  components/common/Card/ProfileHeader.tsx
  components/common/Card/QuoteCard.tsx
  components/common/Card/SongInfo.tsx
  components/common/Card/noteMock.ts
  components/common/ScrollTopBtn.tsx
  components/common/SelectCard.tsx
  components/common/Typo.tsx
  components/common/index.ts
  hooks/useScrollToTop.ts
  tailwind.config.ts
  types/Card/CardType.ts
  utils/getBottomMenu.ts
Labels: ✨Feature, 🎧지혜

#32 [Feat/#31] 하단 모달 구현
  components/common/BottomModal.tsx
  components/common/index.ts
  package-lock.json
  package.json
Labels: ✨Feature, 🎵지원

#30 [Feat/#20] 노트 업로드 프로세스 구현
  app/upload/SearchMusicScreen.tsx
  app/upload/SelectLyricScreen.tsx
  app/upload/UploadFieldScreen.tsx
  app/upload/UploadLinkScreen.tsx
  app/upload/UploadNoteLayout.tsx
  app/upload/UploadNoteScreen.tsx
  app/upload/UploadPlaylistScreen.tsx
  app/upload/UploadTagScreen.tsx
  babel.config.js
  components/Home/CtgryTopBar.tsx
  components/common/LNB.tsx
  components/common/Tags/FilterTags.tsx
  components/common/Tags/TagSection.tsx
  components/common/index.ts
  components/upload/InputField.tsx
  components/upload/MusicInfo.tsx
  components/upload/UploadOptionModal.tsx
  components/upload/index.ts
  components/upload/uploadData.ts
  constants/emotions.ts
  constants/tag.ts
  constants/upload.tsx
  contexts/UploadNoteContext.tsx
  hooks/useTab.ts
  hooks/useTabMenu.ts
  hooks/useYouTubeInfo.ts
  navigation/BottomNavigator.tsx
  navigation/UploadNoteNavigator.tsx
  navigation/UploadStackNavigator.tsx
  package-lock.json
  package.json
  tsconfig.json
  types/upload.ts
  utils/getVisibilityIcon.ts
Labels: ✨Feature, 🎸서연

#40 [Feat/#39] 공통 컴포넌트 스타일 수정
  components/common/Card/DashedLine.tsx
  components/common/Card/NoteCard.tsx
  components/common/Card/ProfileHeader.tsx
  components/common/Card/QuoteCard.tsx
  components/common/Card/SongInfo.tsx
  components/common/Tags/Chip.tsx
  components/common/Typo.tsx
  components/common/index.ts
  types/Card/CardType.ts
Labels: 🎨Design, 🎸서연

#42 [Feat/#35] 플리 업로드 프로세스 구현
  app/_layout.tsx
  app/home/HomeScreen.tsx
  app/upload/UploadNoteLayout.tsx
  app/upload/UploadPlaylistScreen.tsx
  app/upload/note/SearchMusicScreen.tsx
  app/upload/note/SelectLyricScreen.tsx
  app/upload/note/UploadFieldScreen.tsx
  app/upload/note/UploadLinkScreen.tsx
  app/upload/note/UploadNoteLayout.tsx
  app/upload/note/UploadTagScreen.tsx
  app/upload/playlist/PlaylistTagScreen.tsx
  app/upload/playlist/PlaylistVisibilityScreen.tsx
  app/upload/playlist/QuoteNoteScreen.tsx
  app/upload/playlist/UploadPlaylistScreen.tsx
  components/common/BaseModal.tsx
  components/common/BottomMenu.tsx
  components/common/Card/QuoteCard.tsx
  components/common/Card/noteMock.ts
  components/common/Header.tsx
  components/upload/CollectionInfo.tsx
  components/upload/InputField.tsx
  components/upload/MemoInputModal.tsx
  components/upload/PlaylistInfo.tsx
  components/upload/QuoteCollectionList.tsx
  components/upload/QuoteNoteList.tsx
  components/upload/index.ts
  contexts/UploadNoteContext.tsx
  contexts/UploadPlaylistContext.tsx
  hooks/useUploadTag.ts
  navigation/BottomNavigator.tsx
  navigation/UploadNoteNavigator.tsx
  navigation/UploadPlaylistNavigator.tsx
  navigation/UploadStackNavigator.tsx
  package-lock.json
  package.json
  types/Card/CardType.ts
  types/upload.ts
  utils/getVisibility.ts
  utils/getVisibilityIcon.ts
Labels: ✨Feature, 🎸서연

#43 [Feat/#36] 토스트 컴포넌트 및 useToast 훅 구현
  app/_layout.tsx
  app/upload/note/UploadTagScreen.tsx
  app/upload/playlist/PlaylistTagScreen.tsx
  components/common/Toast.tsx
  components/common/index.ts
  contexts/ToastContext.tsx
Labels: ✨Feature, 🎸서연

#45 [Feat/#44] 아이콘 파일 추가
  assets/svgs/IcDownload.tsx
  assets/svgs/IcLink.tsx
  assets/svgs/IcShare.tsx
  assets/svgs/IcUploadNote.tsx
  assets/svgs/index.ts
  components/common/BottomModal.tsx
Labels: ✨Feature, 🎸서연
